name: Build
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix packages
        uses: diamondburned/cache-install@main
        with:
          auto-optimise: true
          shell-file: shell.nix

      - name: Build
        run: ./build_frontend.ts

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
